<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
		<RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="eToro.Trading.Framework.Configuration" Version="$(FrameworkBuildVersion)" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\dor-cytech-poc1.Domain\dor-cytech-poc1.Domain.csproj" />
		<ProjectReference Include="..\dor-cytech-poc1.Infrastructure\dor-cytech-poc1.Infrastructure.csproj" />
	</ItemGroup>

</Project>
